language: r
cache: packages

r:
  - release
  - devel
  - bioc-release

sudo: false

addons:
  apt:
    packages:
      - qpdf

r_packages:
  - magrittr 
  - ape
  - compositions
  - phangorn
  - stats 
  - phytools 
  - caper 
  - scatterplot3d 
  - Biostrings
  - biglm 
  - parallel 
  - testthat

before_install:
  - curl -OLs http://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
  # add our launchpad repo which has (inter alia) the r-cran-rbenchmark package
  - sudo add-apt-repository -y ppa:edd/misc
  - ./run.sh bootstrap

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

script: 
  - Rscript -e "library(testthat); test_check('phylofactor')"

notifications:
  email:
    on_success: change
    on_failure: always
